acme_hello_homepage:
    path:     /hello/{name}
    defaults: { _controller: AcmeHelloBundle:Default:index }
 
hola:
    path:     /hola/{name}
    defaults: { _controller: AcmeHelloBundle:Hola:index }
